### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by izederf** [ajayrandhawa/Keylogger#14]
i did a quick virus total scan of the winrar archive and it turned out to be malicious, can you explain?

**Comment by lblanke210** [comment]
He answers his telegram. Check his profile page then it’s on there somewhere.

**Comment by cyborg-moonbase** [comment]
> i did a quick virus total scan of the winrar archive and it turned out to be malicious, can you explain?

Hmm…

 I wonder if he infected the Keylogger zip file with some sort of keylogger… 🤔

and what if *that* keylogger also has a keylogger in it? 👀 And *that* keylogger has a keylogger in it too…??👀 … and that one,👀 and that one… 👀👀

surely one of these malicious keyloggers must be just a normal malicious keylogger that’s not infected with some sort of malicious keylogger!! 🫣

where will this recursion of madness end??? 🤯

**Comment by vyshnav8486** [comment]
Why most antivirus software can't detect software keyloggers ?

**Comment by ajayrandhawa** [comment]
> > i did a quick virus total scan of the winrar archive and it turned out to be malicious, can you explain?
> 
> Hmm…
> 
> I wonder if he infected the Keylogger zip file with some sort of keylogger… 🤔
> 
> and what if _that_ keylogger also has a keylogger in it? 👀 And _that_ keylogger has a keylogger in it too…??👀 … and that one,👀 and that one… 👀👀
> 
> surely one of these malicious keyloggers must be just a normal malicious keylogger that’s not infected with some sort of malicious keylogger!! 🫣
> 
> where will this recursion of madness end??? 🤯

Don't Worry its Basic One, Zip File Only for Working Code
