### ISSUE TITLE
compil error

### ISSUE THREAD

**Issue by protrading104** [ajayrandhawa/Keylogger#15]
1>Keylogger.cpp
keylogger.cpp(17): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
keylogger.cpp(22): error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\windows kits\10\include\10.0.17763.0\ucrt\stdio.h(208): note: see declaration of 'fopen'
1>c:\scripts\keylogger\keylogger\keylogger\keylogger.cpp(26): error C4996: 'ctime': This function or variable may be unsafe. Consider using ctime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\windows kits\10\include\10.0.17763.0\ucrt\time.h(476): note: see declaration of 'ctime'
1>c:\scripts\keylogger\keylogger\keylogger\keylogger.cpp(43): error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\windows kits\10\include\10.0.17763.0\ucrt\stdio.h(208): note: see declaration of 'fopen'

**Comment by SeiV-K** [comment]
Fix it and stop being stupid idiot

**Comment by ajayrandhawa** [comment]
Issue and Answer visual studio Shows
